version: '2'
services:
    eureka-naming-server:
        build: eureka-naming-server
        mem_limit: 512M
        ports:
            - "8070:8070"
    forex-service:
        build: forex-service
        mem_limit: 512M
        ports:
            - "8000:8000" 
    currency-conversion-service:
        build: currency-conversion-service
        mem_limit: 512M
        ports:
            - "8100:8100"
