version: '2'
services:
    rabbitmq:
        container_name: rabbitmq-server
        image: 'rabbitmq:management'
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5673:5672"
            - "15673:15672"
    registryservice:
        build: registryservice
        mem_limit: 512M
        ports:
            - "8761:8761"
    configservice:
        build: configservice
        mem_limit: 512M
        ports:
            - "8888:8888"
        depends_on:
            - rabbitmq    
    counterservice:
        build: counterservice
        mem_limit: 512M
        ports:
            - "8889:8889"
    gatewayservice:
        build: gatewayservice
        mem_limit: 512M
        ports:
            - "9999:9999"
        links:
            - counterservice:counterservice
            - registryservice:registryservice
        depends_on:
            - counterservice
            - registryservice