spring:
  application:
    name: forex-service

server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-naming-server:8070/eureka/
  instance:
    hostname: eureka-naming-server