properties([parameters([choice(choices: ['master', 'featute1', 'feature2'], description: 'Select the branch to build', name: 'branch')])])
pipeline {
    agent any 
    stages {
        stage('Git Checkout') {
            steps {
                echo "Pulling changes from the branch selected by user {$params.branch}"
                git credentialsId: '25f21359-f1e3-40c4-a8e6-edbe69d4e1ab', url: 'https://github.com/muralimanohard/myexamples.git', branch: "{$params.branch}"
            }
        }
        
    }
  }
