pipeline {
    agent any 
    stages {
        stage('Git Checkout') {
            steps {
                echo 'Git Checkout' 
                git credentialsId: '25f21359-f1e3-40c4-a8e6-edbe69d4e1ab', url: 'https://github.com/muralimanohard/myexamples.git'
            }
        }
        
        stage('Maven Build') {
            steps {
                echo 'Maven Build'
                dir("counter-microservices-series-docker/registryservice") {
                    withMaven(maven : 'apache-maven-3.6.0') {
                       bat "mvn clean install -DskipTests"
                    }
                    
                }

            }
        }
        
        stage('Docker Purge') {
           steps {
              echo 'Deleting docker images'
              bat 'docker image prune -fa'

         deleteDir()

         }

     }
  }
}